### ISSUE TITLE
Calculation of degree matrix

### ISSUE THREAD

**Issue by hzau96yhz** [lixinustc/GraphAdapter#3]
Hello！I have a question about the paper. 
![image](https://github.com/lixinustc/GraphAdapter/assets/53745234/f8034f90-c379-46b3-94cd-1506509e3708)
Is a text/visual knowledge subgraph a kind of complete graph? According to the discription in the paper，it seems to calculate the cosine similarity between any two prompts embeddings.
The formula for calculating the degree matrix(below) is a little confusing, but it seems that the diagonal elements of the matrix are all 2K at the end of the calculation. I don't know if that's right.
![image](https://github.com/lixinustc/GraphAdapter/assets/53745234/3117d6d7-8b7a-46eb-8ee0-bca0d77adee1)

**Comment by hzau96yhz** [comment]
Sorry to bother you again, but there is one more question.
During the optimization process, each prompt text feature used for classification will be added to the subgraph.
Will a node be removed from the original image after it is added for the first time?Or continue to add the second node on the graph after the first node is added

**Comment by lixinustc** [comment]
Since the CVPR deadline, I will provide the response after CVPR. Sorry for that.

**Comment by hzau96yhz** [comment]
Hi！Sorry to bother you again! 
Now would you mind answering the questions I raised earlier.

**Comment by lixinustc** [comment]
Sorry for the late response, the p is set as -0.5, therefore, it is not 2K here for the D matrix. You can print it with our codebase. Thanks.
