### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by cailincan0129** [lixinustc/GraphAdapter#6]
Excellent work! When will you release the code? I am looking forward to your release!

**Comment by lixinustc** [comment]
Thanks for your attention. It has been partially released.

**Comment by smurf-1119** [comment]
So will it be completely released?

**Comment by lixinustc** [comment]
Sorry for the late since I have lots of deadlines. I will upload the full code soon.

**Comment by rongtongxueya** [comment]
mark
